### ISSUE TITLE
Missing technical requirements - Lab#9

### ISSUE THREAD

**Issue by elaewin** [luayghazwan/twitter-client#11]
You are still missing the following technical requirements:

* In TweetDetailViewController.swift:

  * Create a View Feed button.

* When the View Feed button is clicked, the user should segue to a 3rd view controller that will show that user's timeline. The api url is "https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=" but you will need to ensure that you pass in the username as a parameter to this url.

* Convert your UITableViewCell subclass(TweetCell) to use a Nib, so you can share the same cell for both the HomeTimelineViewController and the UserTimelineViewController.
* Import an image asset into the asset catalog with the appropriate corresponding image sizes.
* Implement a UITableViewHeaderView on your ViewController.swift that displays the image added to the asset catalog.

**Comment by luyounus** [comment]
Technical requirements met.

**Comment by elaewin** [comment]
You are still missing the requirements for the View Feed button and the UserTimelineViewController with the tweet detail user's feed.
